version: '3'
services:
  yolov7:
    build: .
    container_name: 'yolov7'
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8g'
